language: node_js

before_install:
  - sudo apt-get update
  - sudo apt-get install cmake 

script:
  - "cd client/src/main/c++/"
  - "mkdir build -p"
  - "cd build"
  - "cmake -DCMAKE_TOOLCHAIN_FILE=../Linux-gcc-i686.cmake ../" 
  - "make"
  - "make check"

notifications:
  email: false
