language: node_js

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install cmake libboost-all-dev mingw-w64 wine # binutils-mingw-w64 gcc-mingw-w64 binutils-mingw-w64 gcc-mingw-w64 # mingw-w64-dev

env:
  - TOOLCHAIN_FILE=Linux-gcc-i686
  - TOOLCHAIN_FILE=Windows-mingw-i686

script:
  - "cd client/src/main/c++/"
  - "mkdir build -p"
  - "cd build"
  - "cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain/$TOOLCHAIN_FILE.cmake ../" 
  - "make check"

notifications:
  email: false
