language: node_js

before_install:
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install cmake libboost-system-dev libboost-program-options-dev libboost-filesystem-dev libboost-test-dev mingw-w64 wine gcc-mingw-w64

env:
  - TOOLCHAIN_FILE=Linux-gcc-i686
  - TOOLCHAIN_FILE=Windows-mingw-i686

script:
  - "cd client/src/main/c++/"
  - "mkdir build -p"
  - "cd build"
  - "cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain/$TOOLCHAIN_FILE.cmake ../" 
  - "make check"

notifications:
  email: false
