language: node_js

before_install:
  - sudo apt-get update
  - sudo apt-get install cmake libboost-dev

script:
  - "cd client/src/main/c++/"
  - "mkdir build -p"
  - "cd build"
  - "cmake -DBoost_DEBUG=1 -DCMAKE_TOOLCHAIN_FILE=../toolchain/Linux-gcc-i686.cmake ../" 
  - "make"
  - "make check"

notifications:
  email: false
